[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Jon Bergli Heier <snakebite@jvnv.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
num-integer = "0.1"
binary-heap-plus = "0.2"
